config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>'home#index'
  get 'edit_user' => 'home#edit_user'
  post 'update_user' => 'home#update_user'
  get 'users_list' => "home#users_list"
  get 'profile' => "home#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar, :avatar_cache, :address, :phone_number])
        devise_parameter_sanitizer.permit(:account_update, keys: [ :avatar, :avatar_cache, :address, :phone_number])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index        
    end

    def edit_user
        @user = User.find params[:format] 
    end

    def update_user
        @user = User.find params[:format] 
        @user.address = params[:address]
        @user.save!
    end
    
    def users_list
        @users = User.all.where(admin: false).order('updated_at DESC')
    end

    def profile
        @user = current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_inline_form.html.erb
<%= form_with url: update_user_path(user), class: 'divTableRow', id: dom_id(user, 'inline_form'), remote: true do |f| %> 
  <div class="divTableCell">
      #<%= user.id %>
  </div>

  <div class="divTableCell">
      <%= user.name %>
  </div>

  <div class="divTableCell">
      <%= user.email %>
  </div>

  <div class="divTableCell">        
      <%= user.phone_number %>        
  </div>

  <div class="divTableCell">
    <%= f.text_field :address, autofocus: true %>
  </div>
  <div class="divTableCell">
    <%= f.submit "Update", class: "btn btn-sm btn-primary" %>
  </div>
<% end %>

app/views/home/edit_user.js.erb
document.getElementById('<%= dom_id(@user) %>').insertAdjacentHTML('afterend', "<%= j render 'inline_form', user: @user %>");
document.getElementById('<%= dom_id(@user) %>').style.display = 'none';

app/views/home/index.html.erb
<div class="row">
    <div class="card mt-5 text-center" style="width: 18rem; margin: 0 auto;">
        <div class="card-body">
            <p class="card-text">Welcome To Solbeg</p>            
        </div>
    </div>
</div>

app/views/home/profile.html.erb
<div class="row mt-5">
	<div class="col-4">
		<div class="card" style="width: 18rem;">
			<% if @user.avatar_url.present? %>
				<%= image_tag @user.avatar_url %>	
			<% else %>
				<%= image_tag("/NoImageFound.jpg.png") %>
			<% end %>
		</div>
	</div>
	<div class="col-4">
		<table class="table">
			<tbody>
					<tr>
						<th>Name</th>
							<td><%= @user.name %></td>
					</tr>
					<tr>
						<th>Email</th>
						<td><%= @user.email %></td>
					</tr>
					<tr>
						<th>Contact</th>
						<td><%= @user.phone_number %></td>
					</tr>
					<tr>
						<th>Address</th>
						<td><%= @user.address %></td>
					</tr>					
			</tbody>
		</table>
	</div>
	<div class="col-4">		
		<%= link_to "Edit Details", edit_user_registration_path, class: "btn btn-secondary" %>					
	</div>
</div>

app/views/home/update_user.js.erb
alert("updated successfully");
location.reload();

app/views/home/users_list.html.erb
<h3>Users List</h3>

<div class="divTable blueTable">
    <div class="divTableHeading">
        <div class="divTableRow">
            <div class="divTableHead">#</div>
            <div class="divTableHead">Name</div>
            <div class="divTableHead">Email</div>
            <div class="divTableHead">Phone Number</div>
            <div class="divTableHead">Address</div>
            <div class="divTableHead">Action</div>
        </div>
    </div>
    <div class="divTableBody">
        <% if @users.present? %>
            <% @users.each do |user| %>
            
                <%= content_tag :div, class: 'divTableRow', id: dom_id(user) do %>
                    <div class="divTableCell"><%= user.id %> </div>
                    <div class="divTableCell"><%= user.name %> </div>
                    <div class="divTableCell"><%= user.email %> </div>
                    <div class="divTableCell"><%= user.phone_number %></div>
                    <div class="divTableCell"><%= user.address %></div>
                    <div class="divTableCell"> <%= link_to "Edit", edit_user_path(user), class: 'btn btn-sm btn-secondary', remote: true %> </div>
                <% end %>
            
            <% end %>
        <% end %>
    </div>
</div>
    

app/views/layouts/_footer.html.erb
<footer class="bg-dark paddingTop30 text-sans-serif">
  <div class="mt-4 pt-4 pb-4">
    <div class="row">
      <div class="col-sm-12 text-center text-uppercase">
        <h6 class="text-light">Copyright &copy; Manish</h6>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Solbeg", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active ">
        <% if user_signed_in? && current_user.admin == false %>
          <%= link_to "Profile", profile_path, class: 'btn btn-info' %>
          <%= link_to "Sign Out", destroy_user_session_path, class: 'btn btn-info', :method => :delete %>
        <% elsif user_signed_in? && current_user.admin == true %>
          <%= link_to "Profile", profile_path, class: 'btn btn-info' %>
          <%= link_to "Users List", users_list_path, class: 'btn btn-info' %>
          <%= link_to "Sign Out", destroy_user_session_path, class: 'btn btn-info', :method => :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: 'btn btn-info', :method => :get %>
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-info', :method => :get %>
        <% end %>
      </li>        
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      <% end %>
      <%= yield %>
    </div>
    <%= render partial: "layouts/footer" %>
  </body>
</html>